#!/usr/bin/env python3
"""Regenerate the coverage map: what holds each rule, and what exercises each holder.

A hand-kept coverage table lies within a release (PATTERNS §6/§7) — this one is assembled
from the tree itself: every `enforced_by:` the corpus states, every validator and hook that
ships, every test suite beside them, every scenario in the runsheet. Rates are deliberately
NOT copied here — they live in `evals/RUNS.md`, dated; a copied rate is a stale claim.

Usage: python3 scripts/coverage-map.py   (from the repo root; writes evals/COVERAGE.md)
"""
import glob
import re
from collections import Counter
import sys
from pathlib import Path

OUT = Path("evals/COVERAGE.md")


def first_comment(path):
    for line in Path(path).read_text(encoding="utf-8", errors="replace").splitlines():
        s = line.strip()
        if s.startswith("#!") or not s:
            continue
        if s.startswith("#"):
            return s.lstrip("# ").rstrip(".")
        if s.startswith('"""'):
            return s.strip('"').rstrip(".")
        break
    return ""


def main():
    enforced = Counter()
    for f in glob.glob("*.md") + glob.glob("templates/*.md"):
        for m in re.finditer(r"`?enforced_by[:\s]+`?\s*([a-z-]+)", Path(f).read_text(
                encoding="utf-8", errors="replace"), re.I):
            enforced[m.group(1).lower()] += 1

    validators = [(Path(f).name, first_comment(f)) for f in sorted(glob.glob("scripts/*.py"))
                  if not Path(f).name.startswith("test-")]
    hooks = [(Path(f).name, first_comment(f)) for f in sorted(glob.glob("hooks/*"))
             if Path(f).suffix in (".py", ".sh")]
    tests = [(Path(f).name, first_comment(f)) for f in sorted(glob.glob("scripts/test-*.sh"))]
    rows = [r for r in Path("evals/runsheet.tsv").read_text(encoding="utf-8").splitlines()
            if r and not r.startswith("#")]
    fixtures = sorted(set(r.split("\t")[1] for r in rows if "\t" in r))

    L = ["# Coverage — what holds each rule, and what exercises each holder",
         "",
         "*Generated by `scripts/coverage-map.py` — edit the tree, not this file.*",
         "",
         "**A rule is only as covered as its weakest layer**: a stated `enforced_by`, a "
         "holder that ships, a test that exercises the holder, and a scenario that measures "
         "the behaviour. This map lists each layer from the tree itself; **rates are not "
         "copied here** — they live in `evals/RUNS.md`, dated, where a rate belongs.",
         "",
         "## What the corpus says holds its rules",
         ""]
    for k, v in enforced.most_common():
        L.append(f"- `{k}` — stated {v}×")
    L += ["", "The register of gates and the prose-only list: `permissions.md`.",
          "", "## Validators that ship", ""]
    L += [f"- `scripts/{n}` — {d}" for n, d in validators]
    L += ["", "## Hooks that ship", ""]
    L += [f"- `hooks/{n}` — {d}" for n, d in hooks]
    L += ["", "## Tests that exercise the holders (run by `scripts/preflight.sh`)", ""]
    L += [f"- `scripts/{n}` — {d}" for n, d in tests]
    L += ["", "## Behavioural scenarios",
          "",
          f"- **{len(rows)} runsheet rows** over **{len(fixtures)} fixtures** "
          f"({' · '.join(fixtures)})",
          "- scenario text: `evals/README.md` · `evals/new-scenarios.md` — rates and their "
          "dates: `evals/RUNS.md`",
          ""]
    body = "\n".join(L)
    # `--check` exists so preflight can verify freshness without WRITING. A checker that
    # mutates the tree it checks leaves a failed run with uncommitted changes, and in a
    # read-only checkout it cannot run at all.
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current == body:
            return 0
        print(f"{OUT} is stale — run `python3 scripts/coverage-map.py` and stage the result")
        return 1
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT} — {len(enforced)} enforcement kinds · {len(validators)} validators · "
          f"{len(hooks)} hooks · {len(tests)} test suites · {len(rows)} scenario rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
